cmake_minimum_required(VERSION 3.28)
project(HW_1)

set(CMAKE_CXX_STANDARD 14)

include_directories(.)

add_executable(HW_1
        main26a1.cpp
        TechSystem26a1.cpp
        TechSystem26a1.h
        wet1util.h
        AVL_Tree_1.h
        student.h
        Student.cpp
        Course.h
        Course.cpp
)
